### ISSUE TITLE
RuntimeException when using TransformPushFiltersIntoBGP with OPTIONAL and !BOUND()

### ISSUE THREAD

**Issue by jindrichmynarz** [SmartDataAnalytics/jena-sparql-api#13]
Applying `TransformPushFiltersIntoBGP` to queries with OPTIONAL and !BOUND, such as the following, throws `RuntimeException should not happen`:

```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?concept
WHERE {
  ?concept a skos:Concept .
  OPTIONAL {
    ?concept skos:broader ?broader .
  }
  FILTER (!BOUND(?broader))
}
```

Tested with 3.1.1-1-SNAPSHOT.

**Comment by Aklakan** [comment]
The "should not happen" exception has been removed; if the transformer does not find itself applicable to the current part of the sparql algebra tree, it will do nothing rather than throwing the exception.
