### ISSUE TITLE
Some examples for the sparql-ext module would be nice

### ISSUE THREAD

**Issue by BonaBeavis** [SmartDataAnalytics/jena-sparql-api#18]
Those [datasets](https://github.com/QROWD/trento-bike-racks/tree/master/datasets) could provide examples.

**Comment by Aklakan** [comment]
There is a function reference at the sparql extension project directly:
https://github.com/SmartDataAnalytics/jena-sparql-api/tree/master/jena-sparql-api-sparql-ext

And several usage examples are part of the rdf processing toolkit:
https://github.com/SmartDataAnalytics/RdfProcessingToolkit/tree/develop/doc
