### ISSUE TITLE
cb.equal(s.get("variableName"), "Some string") does not return any results

### ISSUE THREAD

**Issue by AlexTo** [SmartDataAnalytics/jena-sparql-api#27]
Hi
I have a class like this 
```
@Data
@RdfType("p0:Statement")
public class Statement {
    @IriNs("p0")
    private String statementLabel;
    ...
```
In my code, if I select like this:

```
List<Statement> stmts = JpaUtils.getResultList(em, Statement.class, (cb, cq) -> {
            Root<Statement> r = cq.from(Statement.class);
            cq.select(r)
            ;
        });
stmts.forEach(stmt -> System.out.println(stmt.getStatementLabel()));
```

Then I could see in the console

```
...
Elaboration
Achievement standard
Elaboration
Content description
...
```

In my MarkLogic triplestore, the p0:statementLabel is a lexical with language tag @en-au like so:
```
p0:subj-1 p0:statementLabel "Elaboration"@en-au ;
p0:subj-2 p0:statementLabel "Content description"@en-au ;
```

**Problems:**

If I add a WHERE clause to my SELECT to select only subj with statementLabel equals "Elaboration", I got no result

```
List<Statement> stmts = JpaUtils.getResultList(em, Statement.class, (cb, cq) -> {
            Root<Statement> r = cq.from(Statement.class);
            cq.select(r).where(cb.equal(r.get("statementLabel"), "Elaboration"));
            ;
        });
```

Any idea? thanks a lot

Regards

**Comment by Aklakan** [comment]
Hm, there has to be an exact match on the language tag for this to work.
One approach to accomplish this would be to introduce an new @Lang annotation to mark String properties as susceptible to language settings, and then allow configuration of the language on the RDFMapperEngine.
Unfortunately, this is not in place yet.

**Comment by Aklakan** [comment]
The pojo-rdf mapping is discontinued in favor of the much more prowerful Resource-based proxy mapper module
